-- MySQL Script generated by MySQL Workbench
-- Sat Nov 29 15:27:07 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema atanaskaandmarin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atanaskaandmarin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atanaskaandmarin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `atanaskaandmarin` ;

-- -----------------------------------------------------
-- Table `atanaskaandmarin`.`guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atanaskaandmarin`.`guests` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `rsvp` ENUM('Y','N','M') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `atanaskaandmarin`.`guests` (`email` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
